# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapeless < Formula
  desc "Tapeless CLI"
  homepage "https://tapeless.app"
  version "0.0.12"
  license "proprietary"

  on_macos do
    on_intel do
      url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.0.12/tapeless_Darwin_x86_64.tar.gz"
      sha256 "bb04572368d16684562de69ce4cc8ab28b4e840d9d252bb8a7bba36932f0a4e4"

      def install
        bin.install "tapeless"
      end
    end
    on_arm do
      url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.0.12/tapeless_Darwin_arm64.tar.gz"
      sha256 "eb724f52c4b11ecd48db62155eb28a51488a64755401456cf4045fbca4b785c1"

      def install
        bin.install "tapeless"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.0.12/tapeless_Linux_x86_64.tar.gz"
        sha256 "cd6b4f21882a59e0426ca8d00f48c239b484ab89eea3980c5d2c404b01904741"

        def install
          bin.install "tapeless"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.0.12/tapeless_Linux_arm64.tar.gz"
        sha256 "eecceb3cc5f615f8cc5cda09061fd8cbc2985144e6673e7f1f37bebce296a368"

        def install
          bin.install "tapeless"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tapeless version")
  end
end
