# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapeless < Formula
  desc "Tapeless CLI"
  homepage "https://tapeless.app"
  version "0.1.0"
  license "proprietary"

  on_macos do
    on_intel do
      url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Darwin_x86_64.tar.gz"
      sha256 "5c15c58979a9b40791215f210edb06702115d358e5e494e9c99d0e9851def7b2"

      def install
        bin.install "tapeless"
      end
    end
    on_arm do
      url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Darwin_arm64.tar.gz"
      sha256 "2f074f0b4fedd5fc8259fe0a663bbef8e4c58460b6d48ad7194c55fc40d7fbbd"

      def install
        bin.install "tapeless"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Linux_x86_64.tar.gz"
        sha256 "de6adff5826a07f9434ceb05096eba0c026715dc991bda7c735ccc002200c2b1"

        def install
          bin.install "tapeless"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Linux_arm64.tar.gz"
        sha256 "15bfaa0fd523882d97f37052adfac07649e0b9b84524b93bad81894b972e6457"

        def install
          bin.install "tapeless"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tapeless version")
  end
end
