# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapeless < Formula
  desc "Tapeless CLI"
  homepage "https://tapeless.app"
  version "0.1.0"
  license "proprietary"

  on_macos do
    on_intel do
      url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Darwin_x86_64.tar.gz"
      sha256 "dd975b1088e191d0c637e5aac079fa0d5e0700a0a66fc431b3453d1acf96a044"

      def install
        bin.install "tapeless"
      end
    end
    on_arm do
      url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Darwin_arm64.tar.gz"
      sha256 "f21bfc809163583ef002d39504c7cb0fa4e4a98b194977493667b8a3a7bfd935"

      def install
        bin.install "tapeless"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Linux_x86_64.tar.gz"
        sha256 "d963f7ce0d5803424f83584e4d283e171302463752cc1b15670c6fe603b070f2"

        def install
          bin.install "tapeless"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Tapeless-App/Tapeless-CLI/releases/download/v0.1.0/tapeless_Linux_arm64.tar.gz"
        sha256 "f6a5597ed5001a605a066ca0a5a946104cef444b565b67299a7203e35e8ba5db"

        def install
          bin.install "tapeless"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tapeless version")
  end
end
